kind: pipeline
type: docker
name: default

steps:
  - name: squid
    image: plugins/docker
    depends_on:
      - clone
    settings:
      dockerfile: squid/Dockerfile
      repo: hsmtkk/squid_kube
      username: hsmtkk
      password:
        from_secret: DOCKER_HUB_TOKEN
      tags:
        - squid
  - name: c-icap
    image: plugins/docker
    depends_on:
      - clone
    settings:
      dockerfile: c-icap/Dockerfile
      repo: hsmtkk/squid_kube
      username: hsmtkk
      password:
        from_secret: DOCKER_HUB_TOKEN
      tags:
        - c-icap
  - name: clamav
    image: plugins/docker
    depends_on:
      - clone
    settings:
      dockerfile: clamav/Dockerfile
      repo: hsmtkk/squid_kube
      username: hsmtkk
      password:
        from_secret: DOCKER_HUB_TOKEN
      tags:
        - clamav

