kind: pipeline
type: docker
name: default

steps:
  - name: squid
    image: plugins/docker
    depends_on:
      - clone
    settings:
      dockerfile: squid/Dockerfile
      repo: hsmtkk/squid_kube
      username: hsmtkk
      password:
        from_secret: DOCKER_HUB_TOKEN
      tags:
        - squid
  - name: url_filter
    image: plugins/docker
    depends_on:
      - clone
    settings:
      dockerfile: url_filter/Dockerfile
      repo: hsmtkk/squid_kube
      username: hsmtkk
      password:
        from_secret: DOCKER_HUB_TOKEN
      tags:
        - url_filter
  - name: virus_scan
    image: plugins/docker
    depends_on:
      - clone
    settings:
      dockerfile: virus_scan/Dockerfile
      repo: hsmtkk/squid_kube
      username: hsmtkk
      password:
        from_secret: DOCKER_HUB_TOKEN
      tags:
        - virus_scan
  - name: pinger
    image: plugins/docker
    depends_on:
      - clone
    settings:
      dockerfile: pinger/Dockerfile
      repo: hsmtkk/squid_kube
      username: hsmtkk
      password:
        from_secret: DOCKER_HUB_TOKEN
      tags:
        - pinger

