kind: pipeline
type: docker
name: default


steps:
  - name: centos
    image: plugins/docker
    settings:
      username: hsmtkk
      password:
        from_secret: GIT_HUB_TOKEN
      repo: docker.pkg.github.com/hsmtkk/squid_kube/centos
      registry: docker.pkg.github.com
      dockerfile: centos/Dockerfile
      tags:
        - latest
        - 8
