kind: pipeline
type: docker
name: default

steps:
  - name: squid
    image: plugins/docker
    depends_on:
      - clone
    settings:
      dockerfile: squid/Dockerfile
      repo: hsmtkk/squid_kube
      username: hsmtkk
      password:
        from_secret: DOCKER_HUB_TOKEN
      tags:
        - squid
  - name: urlfilter
    image: plugins/docker
    depends_on:
      - clone
    settings:
      dockerfile: urlfilter/Dockerfile
      repo: hsmtkk/squid_kube
      username: hsmtkk
      password:
        from_secret: DOCKER_HUB_TOKEN
      tags:
        - urlfilter
  - name: virusscan
    image: plugins/docker
    depends_on:
      - clone
    settings:
      dockerfile: virusscan/Dockerfile
      repo: hsmtkk/squid_kube
      username: hsmtkk
      password:
        from_secret: DOCKER_HUB_TOKEN
      tags:
        - virusscan
  - name: pinger
    image: plugins/docker
    depends_on:
      - clone
    settings:
      dockerfile: pinger/Dockerfile
      repo: hsmtkk/squid_kube
      username: hsmtkk
      password:
        from_secret: DOCKER_HUB_TOKEN
      tags:
        - pinger

