kind: pipeline
type: docker
name: default

steps:
  - name: centos
    image: plugins/docker
    settings:
      username: hsmtkk
      password:
        from_secret: DOCKER_HUB_TOKEN
      repo: hsmtkk/squid_kube
      dockerfile: centos/Dockerfile
      tags:
        - centos-8
  - name: centos-dev
    image: plugins/docker
    depends_on:
      - centos
    settings:
      username: hsmtkk
      password:
        from_secret: DOCKER_HUB_TOKEN
      repo: hsmtkk/squid_kube
      dockerfile: centos-dev/Dockerfile
      tags:
        - centos-dev-8
  - name: openssl
    image: plugins/docker
    depends_on:
      - centos-dev
    settings:
      username: hsmtkk
      password:
        from_secret: DOCKER_HUB_TOKEN
      repo: hsmtkk/squid_kube
      dockerfile: openssl/Dockerfile
      tags:
        - openssl-1.1.1g
  - name: squid
    image: plugins/docker
    depends_on:
      - openssl
    settings:
      username: hsmtkk
      password:
        from_secret: DOCKER_HUB_TOKEN
      repo: hsmtkk/squid_kube
      dockerfile: squid/Dockerfile
      tags:
        - squid-4.11
  - name: c-icap
    image: plugins/docker
    depends_on:
      - centos-dev
    settings:
      username: hsmtkk
      password:
        from_secret: DOCKER_HUB_TOKEN
      repo: hsmtkk/squid_kube
      dockerfile: c-icap/Dockerfile
      tags:
        - c-icap-0.5.6
  - name: clamav
    image: plugins/docker
    depends_on:
      - openssl
    settings:
      username: hsmtkk
      password:
        from_secret: DOCKER_HUB_TOKEN
      repo: hsmtkk/squid_kube
      dockerfile: clamav/Dockerfile
      tags:
        - clamav-0.102.2
