version: "3"
services:
  c-icap:
    image: hsmtkk/squid_kube:c-icap-0.5.6
  clamav:
    image: hsmtkk/squid_kube:clamav-0.102.2
  squid:
    image: hsmtkk/squid_kube:squid-4.11
    ports:
      - "8000:8000"
      