apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlfilter
  labels:
    app: urlfilter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: urlfilter
  template:
    metadata:
      labels:
        app: urlfilter
    spec:
      containers:
      - name: urlfilter
        image: hsmtkk/squid_kube:urlfilter
        ports:
          - containerPort: 1344

---

apiVersion: v1
kind: Service
metadata:
  name: urlfilter
spec:
  type: NodePort
  selector:
    app: urlfilter
  ports:
  - protocol: TCP
    port: 1344
