apiVersion: apps/v1
kind: Deployment
metadata:
  name: virusscan
  labels:
    app: virusscan
spec:
  replicas: 2
  selector:
    matchLabels:
      app: virusscan
  template:
    metadata:
      labels:
        app: virusscan
    spec:
      containers:
      - name: virusscan
        image: hsmtkk/squid_kube:virusscan
        ports:
          - containerPort: 1344

---

apiVersion: v1
kind: Service
metadata:
  name: virusscan
spec:
  type: NodePort
  selector:
    app: virusscan
  ports:
  - protocol: TCP
    port: 1344
